library(lubridate)
library(dplyr)
library(ggplot2)
load("MR.Rdata")
# head(MR)
MR1 <- filter(MR, ATMP != 999 & WTMP != 999)
buoyTimeStr <- paste(MR1$YYYY, MR1$MM, MR1$DD, MR1$hh, sep="-")
# print(buoyDateStr)
MR1$TIME <- ymd_h(buoyTimeStr)
MR1$DATE <- as.double(MR1$YYYY)*10000 + as.double(MR1$MM)*100 + as.double(MR1$DD)
# print(buoyTime[1])
MR2 <- filter(MR1, MM == '05' & hh == '12')
ggplot(MR2, aes(x=DATE, y=ATMP))+geom_point(alpha=0.3)+geom_smooth()
# print(MR2)

